#pragma once

namespace ControlsIds
{
	enum Ids
	{
		//File list
		FILE_LIST = 1001,
		DRIVE_COMBO,
		SPAWN_ENITY_DIALOG_COMBO,
		SPAWN_ENITY_DIALOG_CURRENT_FILE,
		SPAWN_ENITY_DIALOG_NORMALIZED_MESH,
		SPAWN_ENITY_DIALOG_EDIT_X,
		SPAWN_ENITY_DIALOG_EDIT_Y,
		SPAWN_ENITY_DIALOG_EDIT_Z,
		SPAWN_ENITY_DIALOG_BUTTON_OK,
		SPAWN_ENITY_DIALOG_BUTTON_CANCEL,
		//Inspector
		INSPECTOR_EDIT_POSITION_X,
		INSPECTOR_EDIT_POSITION_Y,
		INSPECTOR_EDIT_POSITION_Z,
		INSPECTOR_EDIT_ROTATION_X,
		INSPECTOR_EDIT_ROTATION_Y,
		INSPECTOR_EDIT_ROTATION_Z,
		INSPECTOR_EDIT_SCALE_X,
		INSPECTOR_EDIT_SCALE_Y,
		INSPECTOR_EDIT_SCALE_Z,
		INSPECTOR_ATTACH_TO_TERRAIN_HEIGHT,
		INSPECTOR_DELETE_CURRENT_SELECTED,
		INSPECTOR_TEXT_CURRENT_SELECTED,
		INSPECTOR_GO_CAMERA_TO_OBJECT,
		INSPECTOR_TEXTURE,
		INSPECTOR_PAINT_SIZE,
		INSPECTOR_PAINT_STRENGTH,
		INSPECTOR_PAINT_SIZE_TEXT,
		INSPECTOR_PAINT_STRENGTH_TEXT,
		INSPECTOR_TEXT_ATTACHED_OFFSET,
		INSPECTOR_UPPER_LIMIT,
		INSPECTOR_DOWN_LIMIT,
		INSPECTOR_HEIGHT_LIMIT,
		//Tree
		OBJECT_TREEE,
		//Menu
		MENU_NEW_SCENE,
		MENU_OPEN_SCENE,
		MENU_SAVE_SCENE,
		MENU_SAVE_OBJECTS,
		MENU_SAVE_BLENDMAPS,
		MENU_SAVE_HEIGHTMAPS,
		MENU_ABOUT,
		MENU_QUIT,
		//GUIEditor
		GUI_MAIN_DIALOG,
		GUI_TREE_VIEW,
		//Count
		COUNT
	};
}